---
title: "20191209_OSEAR Prelim Baseline"
author: "Emma"
date: "02/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(here)
library(ggplot2)
library(knitr)
library(lubridate)
library(tableone)
library(forcats)
library(stringr)
library(janitor)
library(plyr)
library(dplyr)
library(qwraps2)
library(gridExtra)
library(rlang)
options(qwraps2_markup = "markdown")
```

## Read in the 6mo data
```{r reading_data, results="hide"}

# Read in 6mo contact data and codebook 
data6 <- read_csv(here::here("Data", "20200311_OSEAR Prelim 6mo data.csv"))
codebook6 <- read_csv(here::here("Data", "20191213_OSEAR 6mo prelim codebook.csv"))

# Fix up column names + select completed cases
colnames(data6) <- colnames(codebook6)
data6 <- data6 %>% 
  dplyr::rename(phonecontact = Colname) %>% 
  filter(done == 1) %>% 
  select(-colldate, -collid)

```


###### WHOQOL-BREF ######

## Scoring WHOQOL-BREF
```{r whoqol_score}

data_who <- data6 %>% 
  select(uid, qol, satisf, pain, med, enjoy, mean, concent, safe, phys, energ, appear, mon, avail, leis, getround, sleep, adl, work, self, relat, sex, frenz, livplace, hserv, transport, blues)

# 1. Check range is 1-5 for all var 
range_who <- data_who %>% 
  select(-uid)

stopifnot(range(range_who, na.rm = TRUE) == c(1, 5))

rm(range_who)


# 2. Flip coding for negatively phrased questions 3 (pain), 4 (med), 26 (blues)
for(var in c('pain', 'med', 'blues')) {
  data_who <- data_who %>% 
    dplyr::mutate(!!var := case_when(get(var) == 1 ~ 5, 
                                     get(var) == 2 ~ 4, 
                                     get(var) == 3 ~ 3, 
                                     get(var) == 4 ~ 2, 
                                     get(var) == 5 ~ 1))
}
  

# 3. Domain raw scores: D1 physical health, D2 psychological health, D3 social relationships, D4 environment
# D1 (need 6) = 3 pain, 4 med, 10 energ, 15 getround, 16 sleep, 17 adl, 18 work
# D2 (need 5) = 5 enjoy, 6 mean, 7 concent, 11 appear, 19 self, 26 blues
# D3 (need 2) = 20 relat, 21 sex , 22 frenz
# D4 (need 6) = 8 safe, 9 phys, 12 mon, 13 avail, 14 leis, 23 livplace, 24 hserv, 25 transport

data_who <- data_who %>% 
  dplyr::mutate(d1_score = 4*rowMeans(data_who[, c('pain', 'med', 'energ', 'getround', 'sleep', 'adl', 'work')], na.rm = TRUE)) %>% 
  dplyr::mutate(d2_score = 4*rowMeans(data_who[, c('enjoy', 'mean', 'concent', 'appear', 'self', 'blues')], na.rm = TRUE)) %>% 
  dplyr::mutate(d3_score = 4*rowMeans(data_who[, c('relat', 'sex', 'frenz')], na.rm = TRUE)) %>% 
  dplyr::mutate(d4_score = 4*rowMeans(data_who[, c('safe', 'phys', 'mon', 'avail', 'leis', 'livplace', 'hserv', 'transport')], na.rm = TRUE))

# WHERE are Q1 (qol) and Q2 (satisf) ??? Not included in the domain scoring.. why?

# Take a look at the results 
summary(data_who$d1_score)
  # Domain 1: Physical Health 
  #  Min.   1st Qu.  Median   Mean    3rd Qu.   Max. 
  #  6.286  12.286   15.429   14.552  17.000    19.429 
hist(data_who$d1_score)

summary(data_who$d2_score)
  # Domain 2: Psychological Health 
  #  Min.   1st Qu.  Median   Mean    3rd Qu.  Max. 
  #  10.67  14.67    16.33    16.04   18.00    20.00 
hist(data_who$d2_score)

summary(data_who$d3_score)
  # Domain 3: Social Relationships
  #  Min.   1st Qu.  Median   Mean    3rd Qu.  Max. 
  #  8.00   14.67    17.33    16.71   20.00    20.00 
hist(data_who$d3_score)

summary(data_who$d4_score)
  # Domain 4: Environment 
  #  Min.   1st Qu.  Median   Mean    3rd Qu.  Max. 
  #  8.50   15.62    17.00    16.47   19.00    20.00 
hist(data_who$d4_score)


# 4. Delete cases with >20% missing data --> Maximum 5/26 can be missing
data_who <- data_who %>% 
  dplyr::mutate(missing = rowSums(is.na(data_who))) %>% 
  filter(missing <6)

# 5. Check domain scores (should be in range 4-20)
range(data_who$d1_score)   # Yep
range(data_who$d2_score)   # Yep
range(data_who$d3_score)   # Yep
range(data_who$d4_score)   # Yep

# 6. Save data set 
#write_csv()

```


## Relabel WHOQOL-BREF responses 
```{r whoqol_relabel}

# Relabel responses via a piped for-loop
for(var in c('pain', 'med', 'enjoy', 'mean', 'concent', 'safe', 'phys', 'energ', 'appear', 'mon', 'avail', 'leis')) {
    data <- data_who %>% 
      dplyr::mutate(!!var := case_when(is.na(get(var)) ~ "Missing", 
                                  get(var) == 1 ~ "Not at all", 
                                  get(var) == 2 ~ "A little", 
                                  get(var) == 3 ~ "A moderate amount", 
                                  get(var) == 4 ~ "Very much", 
                                  get(var) == 5 ~ "An extreme amount", 
                                  TRUE ~ "other"))
  }
  
for(var in c('qol', 'satisf', 'getround')) {
  data <- data %>% 
    dplyr::mutate(!!var := case_when(is.na(get(var)) ~ "Missing", 
                                           get(var) == 1 ~ "Very poor", 
                                           get(var) == 2 ~ "Poor", 
                                           get(var) == 3 ~ "Neither poor nor good", 
                                           get(var) == 4 ~ "Good", 
                                           get(var) == 5 ~ "Very good", 
                                           TRUE ~ "other"))
}

for(var in c('sleep', 'adl', 'work', 'self', 'relat', 'sex', 'frenz', 'livplace', 'hserv', 'transport')) {
  data <- data %>% 
    dplyr::mutate(!!var := case_when(is.na(get(var)) ~ "Missing", 
                                     get(var) == 1 ~ "Very dissatisfied", 
                                     get(var) == 2 ~ "Dissatisfied", 
                                     get(var) == 3 ~ "Neither satisfied nor dissatisfied", 
                                     get(var) == 4 ~ "Satisfied", 
                                     get(var) == 5 ~ "Very satisfied", 
                                     TRUE ~ "other"))
}

data <- data %>% 
  mutate(blues = case_when(is.na(blues) ~ "Missing", 
                           blues == 1 ~ "Never", 
                           blues == 2 ~ "Seldom", 
                           blues == 3 ~ "Quite often", 
                           blues == 4 ~ "Very often", 
                           blues == 5 ~ "Always", 
                           TRUE ~ "other"))


```

# WHOQOL-BREF frequency tables
```{r freq_count_tables}

### WHOQOL-BREF
## Very poor to Very good 
pg_data <- data %>%                                  # Select questions that use very poor > Very good answers
  select(qol, satisf, getround) 

pg_ans <- c("Very poor", "Poor", "Neither poor nor good", "Good", "Very good", "Missing", "other") # Answers

pg_func <- function (a) {                            # Create function! 
  a <- factor(a, levels = pg_ans)                    # Level based on answers
  counts <- table(a)                                 # Create frequency count table 
}

pg_tab <- apply(pg_data, 2, pg_func) %>%             # Apply counting function to selected columns(2) 
  t() %>%                                            # Transpose so answers = columns
  as.data.frame()                                    # Store as data frame 

rm(list = c('pg_data', 'pg_ans', 'pg_func'))         # Clean up 

## Not at all -> An extreme amount
nex_data <- data %>% 
  select(pain, med, enjoy, mean, concent, safe, phys, energ, appear, mon, avail, leis)

nex_ans <- c("Not at all", "A little", "A moderate amount", "Very much", "An extreme amount", "Missing", "other") 

nex_func <- function (b) {
  b <- factor(b, levels = nex_ans) 
  counts <- table(b)
}

nex_tab <- apply(nex_data, 2, nex_func) %>% 
  t() %>% 
  as.data.frame()

rm(list = c('nex_data', 'nex_ans', 'nex_func'))

## Very dissatsfied to Very Satisfied  
sat_data <- data %>% 
  select(sleep, adl, work, self, relat, sex, frenz, livplace, hserv, transport)

sat_ans <- c("Very dissatisfied", "Dissatisfied", "Neither satisfied nor dissatisfied", "Satisfied", "Very satisfied", "Missing", "other") 

sat_func <- function (x) {
  x <- factor(x, levels = sat_ans) 
  counts <- table(x) 
}

sat_tab <- apply(sat_data, 2, sat_func) %>% 
  t() %>% 
  as.data.frame()

rm(list = c('sat_data', 'sat_ans', 'sat_func'))

## Mood 
mood_data <- select(data, blues)

mood_tab <- as.data.frame(table(mood_data)) %>% 
  t()

rm(mood_data)

```




##### MSPSS #####

## MSPSS scoring
```{r mspss_score}

data_mspss <- data6 %>% 
  select(uid, soneed, soshare, famhelp, famemot, socomf, frhelp, frcount, famtalk, frshare, socare, famdecis, frtalk)

# Subcategory range = 4 to 28
# Family (FA) = famhelp, famtalk, famemot, famdecis
# Friends (FR) = frhelp, frcount, frshare, frtalk
# Significant other (SO) = soneed, soshare, socomf, socare

data_mspss <- data_mspss %>% 
  dplyr::mutate(fa_score = rowSums(data_mspss[, c('famhelp', 'famtalk', 'famemot', 'famdecis')], na.rm = TRUE)) %>% 
  dplyr::mutate(fr_score = rowSums(data_mspss[, c('frhelp', 'frcount', 'frshare', 'frtalk')], na.rm = TRUE)) %>% 
  dplyr::mutate(so_score = rowSums(data_mspss[, c('soneed', 'soshare', 'socomf', 'socare')], na.rm = TRUE)) 

# Total score range = 12 to 84
data_mspss <- data_mspss %>%
  dplyr::mutate(mspss_score_total = rowSums(data_mspss[, c('fa_score', 'fr_score', 'so_score')], na.rm = TRUE))

# Summaries! 
summary(data_mspss$fa_score)
# Family sub-score
#  Min.    1st Qu.  Median   Mean    3rd Qu.  Max. 
#  14.00   23.00    24.50    24.23   28.00    28.00 

summary(data_mspss$fr_score) 
# Friend sub-score 
#   Min.   1st Qu.  Median   Mean    3rd Qu.  Max. 
#   11.0   20.0     24.0     22.7    27.0     28.0   

summary(data_mspss$so_score)
# Sig. oth. sub-score
#   Min.   1st Qu.  Median   Mean    3rd Qu.  Max. 
#   4.00   23.25    25.50    22.70   28.00    28.00 

summary(data_mspss$mspss_score_total)
# MSPSS total score 
#   Min.    1st Qu.  Median   Mean    3rd Qu. Max. 
#   42.00   60.00    72.00    69.63   82.25   84.00 


```


## Relabel MSPSS responses + generate frequency counts 
```{r mspss_relabel_count }

for(var in c('soneed', 'soshare', 'famhelp', 'famemot', 'socomf', 'frhelp', 'frcount', 'famtalk', 'frshare', 'socare', 'famdecis', 'frtalk')) {
  data <- data %>% 
    dplyr::mutate(!!var := case_when(is.na(get(var)) ~ "Missing", 
                                     get(var) == 1 ~ "Very Strongly Disagree", 
                                     get(var) == 2 ~ "Strongly Disagree", 
                                     get(var) == 3 ~ "Mildly Disagree", 
                                     get(var) == 4 ~ "Neutral", 
                                     get(var) == 5 ~ "Mildly Agree", 
                                     get(var) == 6 ~ "Strongly Agree", 
                                     get(var) == 7 ~ "Very Strongly Agree", 
                                     TRUE ~ "other"))
}

mspss_data <- data %>% 
  select(soneed, soshare, famhelp, famemot, socomf, frhelp, frcount, famtalk, shfriend, socare, famdecis, frtalk)

mspss_ans <- c("Very Strongly Disagree", "Strongly Disagree", "Mildly Disagree", "Neutral", "Mildly Agree", "Strongly Agree", "Very Strongly Agree", "Missing", "other") 

mspss_func <- function (m) {
  m <- factor(m, levels = mspss_ans) 
  counts <- table(m) 
}

mspss_tab <- apply(mspss_data, 2, mspss_func) %>% 
  t() %>% 
  as.data.frame()

rm(list = c('mspss_data', 'mspss_ans', 'mspss_func'))

mspss_tab <- mspss_tab %>% 
  select(-other)


```


##### Demographics #####
## Demographic characteristics table 
```{r demographics }

# Read in demographics data from APICS screening (age, gender, race, ethnicity)
dem_data_scr <- read_csv(here::here("Data", "20200522_APICS OSEAR screening demographics.csv"))


summary1<- 
      list("Age" = 
             list("median (IQR)" = ~qwraps2::median_iqr(.data$age, digits = 0)), 
           "Gender n (%)" = 
             list("Female"= ~qwraps2::n_perc0(.data$gender == "Female"), 
                  "Male" = ~qwraps2::n_perc0(.data$gender == "Male")), 
           "Race n (%)" = 
             list("White"= ~qwraps2::n_perc0(.data$race == "White"),
                  "Black" = ~qwraps2::n_perc0(.data$race == "Black"), 
                  "Multiracial" = ~qwraps2::n_perc0(.data$race == "Multiracial"),
                  "Asian" = ~qwraps2::n_perc0(.data$race == "Asian"), 
                  "Unknown" = ~qwraps2::n_perc0(.data$race == "Unknown")),
           "Ethnicity n (%)" =
             list("Hispanic or Latino" = ~qwraps2::n_perc0(.data$ethn == "Yes"), 
                  "Not Hispanic or Latino" = ~qwraps2::n_perc0(.data$ethn == "No"), 
                  "Unknown" = ~qwraps2::n_perc0(.data$ethn == "Unknown")))
            "Education n (%)" = 
             list("8th grade or less" = ~qwraps2::n_perc0(.data$ed == "8th grade or less"), 
                  "Some high school, but did not graduate" = ~qwraps2::n_perc0(.data$ed == "Some high school")
                  "High school graduate or GED" = ~qwraps2::n_perc0(.data$ed == "High school graduate or GED"),
                  "Some college or 2-year degree" = ~qwraps2::n_perc0(.data$ed == "Some college or 2-year degree"), 
                  "4-year college graduate" = ~qwraps2::n_perc0(.data$ed == "4-year degree"), 
                  "More than 4-year college degree" = ~qwraps2::n_perc0(.data$ed == "More than 4-year degree"), 
                  "Not available" = ~qwraps2::n_perc0(.data$ed == "Not available / Unknown")))

## Assembling the columns of Table 1 
  tab1<-summary_table(dem_data_scr, summary1)                          

## Print Table 2 
  print(tab1,
      rtitle = "Study Participant Characteristics")

  
#-------------------
# Read in demographics from baseline (education, ADI decile / percentile)
dem_data_bsln <- read_csv(here::here("Data", "2020______.csv"))
# Read in OSEAR enrollment ID list 
osear_ids <- read_csv(here::here("Data", "20200604_OSEAR Enrolled ID List.csv"))
# Create combined OSEAR demographic dataset
dem_data_comb <- 
  
summary1<- 
      list("Age" = 
             list("median (IQR)" = ~qwraps2::median_iqr(.data$age, digits = 0)), 
           "Gender n (%)" = 
             list("Female"= ~qwraps2::n_perc0(.data$gender == "Female"), 
                  "Male" = ~qwraps2::n_perc0(.data$gender == "Male")), 
           "Race n (%)" = 
             list("White"= ~qwraps2::n_perc0(.data$race == "White"),
                  "Black" = ~qwraps2::n_perc0(.data$race == "Black"), 
                  "Multiracial" = ~qwraps2::n_perc0(.data$race == "Multiracial"),
                  "Asian" = ~qwraps2::n_perc0(.data$race == "Asian"), 
                  "Unknown" = ~qwraps2::n_perc0(.data$race == "Unknown")),
           "Ethnicity n (%)" =
             list("Hispanic or Latino" = ~qwraps2::n_perc0(.data$ethn == "Yes"), 
                  "Not Hispanic or Latino" = ~qwraps2::n_perc0(.data$ethn == "No"), 
                  "Unknown" = ~qwraps2::n_perc0(.data$ethn == "Unknown")),
            "Education n (%)" = 
             list("8th grade or less" = ~qwraps2::n_perc0(.data$ed == "8th grade or less"), 
                  "Some high school, but did not graduate" = ~qwraps2::n_perc0(.data$ed == "Some high school")
                  "High school graduate or GED" = ~qwraps2::n_perc0(.data$ed == "High school graduate or GED"),
                  "Some college or 2-year degree" = ~qwraps2::n_perc0(.data$ed == "Some college or 2-year degree"), 
                  "4-year college graduate" = ~qwraps2::n_perc0(.data$ed == "4-year degree"), 
                  "More than 4-year college degree" = ~qwraps2::n_perc0(.data$ed == "More than 4-year degree"), 
                  "Not available" = ~qwraps2::n_perc0(.data$ed == "Not available / Unknown")), 
           "ADI Decile" = 
             list("median (IQR)" = ~qwraps::median_iqr(.data$adi_dec, digits = 0)), 
           "ADI Percentile" = 
             list("median (IQR)" = ~qwraps::median_iqr(.data$adi_perc, digits = 0)))
  


```


