---
title: "20191209_OSEAR Prelim Baseline"
author: "Emma"
date: "02/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(here)
library(ggplot2)
library(knitr)
library(lubridate)
library(tableone)
library(forcats)
library(stringr)
library(janitor)
library(plyr)
library(dplyr)
library(qwraps2)
library(gridExtra)
library(rlang)
options(qwraps2_markup = "markdown")
```

## Read in the 6mo data
```{r reading_data, results="hide"}

# Read in 6mo contact data
data6 <- read_csv(here::here("Data", "20200724_OSEAR 6mo prelim data.csv"))

# Read in codebook, identify preferred colnames
codebook6 <- read_csv(here::here("Data", "20200724_OSEAR 6mo prelim codebook.csv"))
codebook6 <- codebook6[, -1]

# Assign new column names from codebook to 6mo data
colnames(data6) <- colnames(codebook6)

# Get rid of unwanted columns 
data6 <- data6 %>% 
  select(-colldate, -collid)

# Select completed cases 
# Taking a look at mspss_done column: 
#     3028 - 2, WHOQOL and MSPSS no data
#     3061 - NA, WHOQOL done, MSPSS no data
data6_complete <- data6 %>% 
  filter(mspss_done == 1 | uid == 3061)


```


###### WHOQOL-BREF ######

## Scoring WHOQOL-BREF
```{r whoqol_score}

# Following scoring guidelines from WHOQOL-BREF Introduction, Administration & Scoring from WHO Geneva
data_who <- data6_complete %>% 
  select(uid, qol, satisf, pain, med, enjoy, mean, concent, safe, phys, energ, appear, mon, avail, leis, around, sleep, adl, work, self, relat, sex, frenz, livplace, health, transport, blues)

# 1. Check range is 1-5 for all var 
range_who <- data_who %>% 
  select(-uid)

stopifnot(range(range_who, na.rm = TRUE) == c(1, 5))

rm(range_who)


# 2. Flip coding for negatively phrased questions 3 (pain), 4 (med), 26 (blues)
for(var in c('pain', 'med', 'blues')) {
  data_who <- data_who %>% 
    dplyr::mutate(!!var := case_when(get(var) == 1 ~ 5, 
                                     get(var) == 2 ~ 4, 
                                     get(var) == 3 ~ 3, 
                                     get(var) == 4 ~ 2, 
                                     get(var) == 5 ~ 1))
}
  

# 3. Domain raw scores: D1 physical health, D2 psychological health, D3 social relationships, D4 environment
# D1 (need 6) = 3 pain, 4 med, 10 energ, 15 around, 16 sleep, 17 adl, 18 work
# D2 (need 5) = 5 enjoy, 6 mean, 7 concent, 11 appear, 19 self, 26 blues
# D3 (need 2) = 20 relat, 21 sex , 22 frenz
# D4 (need 6) = 8 safe, 9 phys, 12 mon, 13 avail, 14 leis, 23 livplace, 24 health, 25 transport

data_who <- data_who %>% 
  dplyr::mutate(d1_score = 4*rowMeans(data_who[, c('pain', 'med', 'energ', 'around', 'sleep', 'adl', 'work')], na.rm = TRUE)) %>% 
  dplyr::mutate(d2_score = 4*rowMeans(data_who[, c('enjoy', 'mean', 'concent', 'appear', 'self', 'blues')], na.rm = TRUE)) %>% 
  dplyr::mutate(d3_score = 4*rowMeans(data_who[, c('relat', 'sex', 'frenz')], na.rm = TRUE)) %>% 
  dplyr::mutate(d4_score = 4*rowMeans(data_who[, c('safe', 'phys', 'mon', 'avail', 'leis', 'livplace', 'health', 'transport')], na.rm = TRUE))

# Take a look at the results 

## Question 1: Overall perception of QoL
summary(data_who$qol)
hist(data_who$qol, 
     main="Perceived QoL", 
     xlab="Score", 
     xlim=c(0.5,5.5), 
     breaks=c(0.5:5.5))

## Question 2: Satisfaction with health
summary(data_who$satisf)
hist(data_who$satisf, 
     main="Satisfaction with health", 
     xlab="Score", 
     xlim=c(0.5,5.5), 
     breaks=c(0.5:5.5))

## Domain 1: Physical Health
summary(data_who$d1_score)
hist(data_who$d1_score, 
     main="D1 Physical Health", 
     xlab="Score", 
     xlim=c(4,20))

## Domain 2: Psychological Health
summary(data_who$d2_score)
hist(data_who$d2_score, 
     main="D2 Psychological Health", 
     xlab="Score", 
     xlim=c(4,20))

## Domain 3: Social Relationships
summary(data_who$d3_score)
hist(data_who$d3_score, 
     main="D3 Social Relationships", 
     xlab="Score", 
     xlim=c(4,20))

## Domain 4: Environment 
summary(data_who$d4_score)
hist(data_who$d4_score, 
     main="D4 Environment", 
     xlab="score", 
     xlim=c(4,20))


# 4. Delete cases with >20% missing data --> Maximum 5/26 can be missing
data_who <- data_who %>% 
  dplyr::mutate(missing = rowSums(is.na(data_who))) %>% 
  filter(missing <6)

# 5. Check domain scores (should be in range 4-20)
range(data_who$d1_score)   # Yep
range(data_who$d2_score)   # Yep
range(data_who$d3_score)   # Yep
range(data_who$d4_score)   # Yep

# 6. Save data set 
#write_csv()

```


## Relabel WHOQOL-BREF responses 
```{r whoqol_relabel, include=FALSE}

# Relabel responses via a piped for-loop
data <- data_who

for(var in c('pain', 'med', 'enjoy', 'mean', 'concent', 'safe', 'phys', 'energ', 'appear', 'mon', 'avail', 'leis')) {
    data <- data %>% 
      dplyr::mutate(!!var := case_when(is.na(get(var)) ~ "Missing", 
                                  get(var) == 1 ~ "Not at all", 
                                  get(var) == 2 ~ "A little", 
                                  get(var) == 3 ~ "A moderate amount", 
                                  get(var) == 4 ~ "Very much", 
                                  get(var) == 5 ~ "An extreme amount", 
                                  TRUE ~ "other"))
  }
  
for(var in c('qol', 'satisf', 'around')) {
  data <- data %>% 
    dplyr::mutate(!!var := case_when(is.na(get(var)) ~ "Missing", 
                                           get(var) == 1 ~ "Very poor", 
                                           get(var) == 2 ~ "Poor", 
                                           get(var) == 3 ~ "Neither poor nor good", 
                                           get(var) == 4 ~ "Good", 
                                           get(var) == 5 ~ "Very good", 
                                           TRUE ~ "other"))
}

for(var in c('sleep', 'adl', 'work', 'self', 'relat', 'sex', 'frenz', 'livplace', 'health', 'transport')) {
  data <- data %>% 
    dplyr::mutate(!!var := case_when(is.na(get(var)) ~ "Missing", 
                                     get(var) == 1 ~ "Very dissatisfied", 
                                     get(var) == 2 ~ "Dissatisfied", 
                                     get(var) == 3 ~ "Neither satisfied nor dissatisfied", 
                                     get(var) == 4 ~ "Satisfied", 
                                     get(var) == 5 ~ "Very satisfied", 
                                     TRUE ~ "other"))
}

data <- data %>% 
  mutate(blues = case_when(is.na(blues) ~ "Missing", 
                           blues == 1 ~ "Never", 
                           blues == 2 ~ "Seldom", 
                           blues == 3 ~ "Quite often", 
                           blues == 4 ~ "Very often", 
                           blues == 5 ~ "Always", 
                           TRUE ~ "other"))


```

# WHOQOL-BREF frequency tables
```{r freq_count_tables}

### WHOQOL-BREF
## Very poor to Very good 
pg_data <- data %>%                                  # Select questions that use very poor > Very good answers
  select(qol, satisf, around) 

pg_ans <- c("Very poor", "Poor", "Neither poor nor good", "Good", "Very good", "Missing", "other") # Answer choices

pg_func <- function (a) {                            # Create function! 
  a <- factor(a, levels = pg_ans)                    # Level based on answers
  counts <- table(a)                                 # Create frequency count table 
}

pg_tab <- apply(pg_data, 2, pg_func) %>%             # Apply counting function to selected columns(2) 
  t() %>%                                            # Transpose so answers = columns
  as.data.frame()                                    # Store as data frame 

rm(list = c('pg_data', 'pg_ans', 'pg_func'))         # Clean up 

## Not at all -> An extreme amount
nex_data <- data %>% 
  select(pain, med, enjoy, mean, concent, safe, phys, energ, appear, mon, avail, leis)

nex_ans <- c("Not at all", "A little", "A moderate amount", "Very much", "An extreme amount", "Missing", "other") 

nex_func <- function (b) {
  b <- factor(b, levels = nex_ans) 
  counts <- table(b)
}

nex_tab <- apply(nex_data, 2, nex_func) %>% 
  t() %>% 
  as.data.frame()

rm(list = c('nex_data', 'nex_ans', 'nex_func'))

## Very dissatisfied to Very Satisfied  
sat_data <- data %>% 
  select(sleep, adl, work, self, relat, sex, frenz, livplace, health, transport)

sat_ans <- c("Very dissatisfied", "Dissatisfied", "Neither satisfied nor dissatisfied", "Satisfied", "Very satisfied", "Missing", "other") 

sat_func <- function (x) {
  x <- factor(x, levels = sat_ans) 
  counts <- table(x) 
}

sat_tab <- apply(sat_data, 2, sat_func) %>% 
  t() %>% 
  as.data.frame()

rm(list = c('sat_data', 'sat_ans', 'sat_func'))

## Mood 
mood_data <- select(data, blues)

mood_tab <- as.data.frame(table(mood_data)) %>% 
  t()

rm(mood_data)

```




##### MSPSS #####

## MSPSS scoring
```{r mspss_score}

data_mspss <- data6 %>% 
  select(uid, soneed, soshare, famhelp, famemot, socomf, frhelp, frcount, famtalk, frshare, socare, famdecis, frtalk)

# Subcategory range = 4 to 28
# Family (FA) = famhelp, famtalk, famemot, famdecis
# Friends (FR) = frhelp, frcount, frshare, frtalk
# Significant other (SO) = soneed, soshare, socomf, socare

# Group questions into 3 categories: FA, FR, SO
data_mspss <- data_mspss %>% 
  dplyr::mutate(fa_score = rowSums(data_mspss[, c('famhelp', 'famtalk', 'famemot', 'famdecis')], na.rm = TRUE)) %>% 
  dplyr::mutate(fr_score = rowSums(data_mspss[, c('frhelp', 'frcount', 'frshare', 'frtalk')], na.rm = TRUE)) %>% 
  dplyr::mutate(so_score = rowSums(data_mspss[, c('soneed', 'soshare', 'socomf', 'socare')], na.rm = TRUE)) 

# Total score range = 12 to 84
data_mspss <- data_mspss %>%
  dplyr::mutate(mspss_score_total = rowSums(data_mspss[, c('fa_score', 'fr_score', 'so_score')], na.rm = TRUE))

# Summaries! 
## Family sub-score
summary(data_mspss$fa_score)
hist(data_mspss$fa_score)
## Friend sub-score 
summary(data_mspss$fr_score) 
hist(data_mspss$fr_score)
## Sig. oth. sub-score
summary(data_mspss$so_score)
hist(data_mspss$so_score)
## MSPSS total score 
summary(data_mspss$mspss_score_total)
hist(data_mspss$mspss_score_total)

```


## Relabel MSPSS responses + generate frequency counts 
```{r mspss_relabel_count }

for(var in c('soneed', 'soshare', 'famhelp', 'famemot', 'socomf', 'frhelp', 'frcount', 'famtalk', 'frshare', 'socare', 'famdecis', 'frtalk')) {
  data <- data %>% 
    dplyr::mutate(!!var := case_when(is.na(get(var)) ~ "Missing", 
                                     get(var) == 1 ~ "Very Strongly Disagree", 
                                     get(var) == 2 ~ "Strongly Disagree", 
                                     get(var) == 3 ~ "Mildly Disagree", 
                                     get(var) == 4 ~ "Neutral", 
                                     get(var) == 5 ~ "Mildly Agree", 
                                     get(var) == 6 ~ "Strongly Agree", 
                                     get(var) == 7 ~ "Very Strongly Agree", 
                                     TRUE ~ "other"))
}

mspss_data <- data %>% 
  select(soneed, soshare, famhelp, famemot, socomf, frhelp, frcount, famtalk, shfriend, socare, famdecis, frtalk)

mspss_ans <- c("Very Strongly Disagree", "Strongly Disagree", "Mildly Disagree", "Neutral", "Mildly Agree", "Strongly Agree", "Very Strongly Agree", "Missing", "other") 

mspss_func <- function (m) {
  m <- factor(m, levels = mspss_ans) 
  counts <- table(m) 
}

mspss_tab <- apply(mspss_data, 2, mspss_func) %>% 
  t() %>% 
  as.data.frame()

rm(list = c('mspss_data', 'mspss_ans', 'mspss_func'))

mspss_tab <- mspss_tab %>% 
  select(-other)


```





